# netlify.toml  – the “quit skipping dev-deps” edition
[build]
  # first, make sure devDependencies get installed
  command = "npm install --include=dev && npm run build"
  publish = "dist"

[build.environment]
  # force npm to include devDependencies—even though NODE_ENV=production
  NPM_CONFIG_PRODUCTION = "false"
  NODE_VERSION          = "20"     # matches your .node-version or .nvmrc

# SPA fallback for React Router
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
